# Dockerfile

FROM python:3.9
WORKDIR /app
RUN apt-get update && apt-get install -y default-libmysqlclient-dev gcc
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8050
CMD ["python", "app.py"]